# Copie de depart pour /knockback create.
knockbackType: ADVANCED
friction: 2.5
horizontal: 0.45
horizontalOnGround: 1.1
horizontalSprinting: 0.95
horizontalInherit: true
horizontalFriction: 0.35
horizontalKnockbackDeduction: 0.8
extraHorizontal: 0.25
extraVertical: 0.01
vertical: 0.35
verticalOnGround: 1.1
verticalInAir: 0.85
verticalSprinting: 1.0
verticalInherit: false
verticalFriction: 0.35
verticalLimit: 1.2
enableVerticalLimit: false
enableOnePointSeven: true
onePointSevenHorizontal: 0.37
onePointSevenMultiplier: 0.4
slowdown: 0.6
cancelSprint: true
rodHorizontal: 1.1
rodVertical: 0.4
rodSpeed: 1.0
bowBoostDirectional: false
bowBoostKbOnlyShooter: false
bowHorizontal: 0.9
bowVertical: 0.35
bowPunchMultiplier: 1.1
potionFall: 0.05
potionSpeed: 0.5
potionVerticalOffset: -10.0
potionFast: true
potionDrag: 0.99
potionStartForward: 0.0
potionStartHeight: -0.1
potionInheritMotion: 0.0
potionDownEnabled: false
potionDownPitch: 70.0
potionDownSpeed: 0.5
potionDownVerticalOffset: -20.0
hitDelay: 20
hitDelayArrow: 20
comboMode: false
comboHeight: 2.3
comboTicks: 10
comboVelocity: -0.05
