# Serveur practice HCF, beaucoup de joueurs, vue courte.
motd=Aether Practice
server-port=25565
online-mode=true
max-players=400
view-distance=4
gamemode=0
difficulty=1
pvp=true
allow-flight=false
allow-nether=false
generate-structures=false
spawn-monsters=false
spawn-animals=false
spawn-npcs=false
spawn-protection=0
white-list=false
enable-command-block=false
snooper-enabled=false
network-compression-threshold=256
max-tick-time=60000
entity-broadcast-range-percentage=60
use-native-transport=true
player-idle-timeout=0
resource-pack=
level-name=world
level-type=DEFAULT
generator-settings=
